/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * The Calling API
 * Central API contract for The Calling backend and frontend service integration.
 * OpenAPI spec version: 1.1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  GetHealth200,
  ListRequestsParams,
  ListUsersParams,
  NewRequest,
  PostApiAuthLogin200,
  PostApiAuthLoginBody,
  PostApiAuthLogout200,
  RequestList,
  ServiceRequest,
  UpdateRequest,
  User
} from './model'



  export const getTheCallingAPI = () => {
/**
 * Returns the status of the backend API, PostgreSQL database, and Redis cache.
 * @summary Health check endpoint
 */
const getHealth = <TData = AxiosResponse<GetHealth200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/health`,options
    );
  }

/**
 * Validates user credentials and sets a secure HttpOnly JWT cookie.
 * @summary Authenticate user
 */
const postApiAuthLogin = <TData = AxiosResponse<PostApiAuthLogin200>>(
    postApiAuthLoginBody: PostApiAuthLoginBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/login`,
      postApiAuthLoginBody,options
    );
  }

/**
 * Clears the secure HttpOnly JWT cookie by setting it with an expired state.
 * @summary Clear user session
 */
const postApiAuthLogout = <TData = AxiosResponse<PostApiAuthLogout200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/logout`,undefined,options
    );
  }

/**
 * Returns the profile details of the currently logged-in user via JWT session authentication.
 * @summary Get current authenticated user
 */
const getApiUsersMe = <TData = AxiosResponse<User>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/me`,options
    );
  }

/**
 * Returns a list of users, primarily used to populate assignee dropdowns.
 * @summary List users
 */
const listUsers = <TData = AxiosResponse<User[]>>(
    params?: ListUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Creates a new service request. Only Requester role users can create requests.
 * @summary Create a new service request
 */
const createRequest = <TData = AxiosResponse<ServiceRequest>>(
    newRequest: NewRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/requests`,
      newRequest,options
    );
  }

/**
 * Returns a paginated list of service requests. Handlers see all requests, Requesters see only their own.
 * @summary List service requests
 */
const listRequests = <TData = AxiosResponse<RequestList>>(
    params?: ListRequestsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/requests`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Returns full details of a single service request by ID.
 * @summary Get a specific service request
 */
const getRequest = <TData = AxiosResponse<ServiceRequest>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/requests/${id}`,options
    );
  }

/**
 * Updates fields of an existing service request. Only Handler role users can edit.
 * @summary Edit a service request
 */
const updateRequest = <TData = AxiosResponse<ServiceRequest>>(
    id: string,
    updateRequest: UpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/requests/${id}`,
      updateRequest,options
    );
  }

return {getHealth,postApiAuthLogin,postApiAuthLogout,getApiUsersMe,listUsers,createRequest,listRequests,getRequest,updateRequest}};
export type GetHealthResult = AxiosResponse<GetHealth200>
export type PostApiAuthLoginResult = AxiosResponse<PostApiAuthLogin200>
export type PostApiAuthLogoutResult = AxiosResponse<PostApiAuthLogout200>
export type GetApiUsersMeResult = AxiosResponse<User>
export type ListUsersResult = AxiosResponse<User[]>
export type CreateRequestResult = AxiosResponse<ServiceRequest>
export type ListRequestsResult = AxiosResponse<RequestList>
export type GetRequestResult = AxiosResponse<ServiceRequest>
export type UpdateRequestResult = AxiosResponse<ServiceRequest>
