/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * The Calling API
 * Central API contract for The Calling backend and frontend service integration.
 * OpenAPI spec version: 1.1.0
 */

export type ListRequestsScope = typeof ListRequestsScope[keyof typeof ListRequestsScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListRequestsScope = {
  me: 'me',
  all: 'all',
} as const;
