/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * The Calling API
 * Central API contract for The Calling backend and frontend service integration.
 * OpenAPI spec version: 1.1.0
 */
import type { ListRequestsScope } from './listRequestsScope';

export type ListRequestsParams = {
/**
 * Number of requests per page.
 */
limit?: number;
/**
 * Number of requests to skip.
 */
offset?: number;
/**
 * Scope of requests to retrieve. Handlers only.
 */
scope?: ListRequestsScope;
/**
 * Filter requests by assignee ID. Handlers only.
 */
assignee_id?: string;
};
