/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * The Calling API
 * Central API contract for The Calling backend and frontend service integration.
 * OpenAPI spec version: 1.1.0
 */

export type ListRequestsParams = {
/**
 * Number of requests per page.
 */
limit?: number;
/**
 * Number of requests to skip.
 */
offset?: number;
};
