/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * The Calling API
 * Central API contract for The Calling backend and frontend service integration.
 * OpenAPI spec version: 1.1.0
 */
import type { User } from './user';

export type PostApiAuthLogin200 = {
  success?: boolean;
  user?: User;
};
