/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * The Calling API
 * Central API contract for The Calling backend and frontend service integration.
 * OpenAPI spec version: 1.1.0
 */

export type ServiceRequestStatus = typeof ServiceRequestStatus[keyof typeof ServiceRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceRequestStatus = {
  open: 'open',
  in_progress: 'in_progress',
  resolved: 'resolved',
  closed: 'closed',
} as const;
